name: Generate Trophy
on:
  schedule:
    - cron: "0 0 * * *"   # يحدّث كل يوم تلقائيًا
  workflow_dispatch:        # يسمحلك تشغّله يدويًا من تبويب Actions
  push:
    branches: [ main ]

jobs:
  generate-trophy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate trophy image
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: mostafa-kameel
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit trophy
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add trophy.svg
          git commit -m "Update trophy" || echo "No changes to commit"
          git push
